/*

    EnergyMech, IRC bot software
    Copyright (c) 1997-2025 proton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

*/
#define GENCMD_C
#include "config.h"
#include "structs.h"

char	globaldata[MAXLEN];

#include "io.c"

#define HASHDATASZ	256
#define HASHDATAMASK	255

uint8_t	hash[512];
uint8_t	hashmap[512];
uint8_t	hashdata[HASHDATASZ];

#define HEATMAP 1
#ifdef HEATMAP
uint8_t heatmap[HASHDATASZ];
#endif

int	mx,collis,mincoll,randfd,heatmapon;

/*
 *  tolowertab blatantly ripped from ircu2.9.32
 */
const uchar tolowertab[256] =
{
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
        0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
        0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
        ' ',  '!',  '"',  '#',  '$',  '%',  '&',  0x27,
        '(',  ')',  '*',  '+',  ',',  '-',  '.',  '/',
        '0',  '1',  '2',  '3',  '4',  '5',  '6',  '7',
        '8',  '9',  ':',  ';',  '<',  '=',  '>',  '?',
        '@',  'a',  'b',  'c',  'd',  'e',  'f',  'g',
        'h',  'i',  'j',  'k',  'l',  'm',  'n',  'o',
        'p',  'q',  'r',  's',  't',  'u',  'v',  'w',
        'x',  'y',  'z',  '{',  '|',  '}',  '~',  '_',
        '`',  'a',  'b',  'c',  'd',  'e',  'f',  'g',
        'h',  'i',  'j',  'k',  'l',  'm',  'n',  'o',
        'p',  'q',  'r',  's',  't',  'u',  'v',  'w',
        'x',  'y',  'z',  '{',  '|',  '}',  '~',  0x7f,
        0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87,
        0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f,
        0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97,
        0x98, 0x99, 0x9a, 0x9b, 0x9c, 0x9d, 0x9e, 0x9f,
        0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7,
        0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf,
        0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7,
        0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
        0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7,
        0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf,
        0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7,
        0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf,
        0xe0, 0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7,
        0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef,
        0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7,
        0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff
};

#include "onhash.h"

#include "commands.h"

#define __command_hash_9	9
#define __print_hashta_7	7
#define __define_strng_5	5
#define __define_print_3	3
#define __struct_acces_2	2
#define __struct_print_1	1

static const char *getsortedcommand(int pass, int *idxout)
{
	const char *chosen;
	int	j,index;

	chosen = NULL;
	index = -1;
	for(j=0;pre_mcmd[j].name;j++)
	{
		if (pre_mcmd[j].pass == pass)
			continue;
		if (chosen == NULL)
		{
			chosen = pre_mcmd[j].name;
			index = j;
			continue;
		}
		if (strcmp(chosen,pre_mcmd[j].name) > 0)
		{
			chosen = pre_mcmd[j].name;
			index = j;
		}
	}
	*idxout = index;
	return(chosen);
}

void make_mcmd(int mode)
{
	const char *cmdstr;
	char	tmp[257];
	int	i,j,cmdidx,pass,fd,h;
	int	cmdcount;
	OnMsg	v;

	if (mode == 0)
	{
		unlink("mcmd.h");
		fd = open("mcmd.h",O_WRONLY|O_CREAT|O_TRUNC,0644);
	}
	if (mode == 1)
	{
		fd = 1;
	}

	collis = 0;
	pass = __command_hash_9;
	cmdcount = 0;

	to_file(fd,"/""* This file is automatically generated from gencmd.c *""/\n");
	to_file(fd,"#ifndef TEST\n#ifndef MCMD_H\n#define MCMD_H 1\n\n");

	while(pass)
	{
		if (pass == __command_hash_9)
		{
			memset(hash,0,sizeof(hash));
			memset(hashmap,255,sizeof(hashmap));
			j = 0;
			if (randfd < 0)
			{
				randfd = open("hashdata.cache",O_RDONLY);
				if (randfd > 0)
				{
					j = read(randfd,hashdata,sizeof(hashdata));
					close(randfd);
					if (j == sizeof(hashdata))
						to_file(2,"gencmd: hashdata recovered from hashdata.cache\n");
				}
				randfd = open("/dev/urandom",O_RDONLY);
				if (randfd < 0)
				{
					to_file(2,"gencmd: Fatal error: unable to create random hashdata from /dev/urandom!\n");
					exit(50);
				}
			}
			if (j < sizeof(hashdata))
			{
				j = read(randfd,hashdata,sizeof(hashdata));
			}
		}
		if (pass == __print_hashta_7)
		{
		}
		if (pass == __struct_acces_2)
		{
			to_file(fd,"OnMsg_access acmd[] =\n{\n");
		}
		if (pass == __struct_print_1)
		{
			to_file(fd,"const OnMsg mcmd[] =\n{\n");
		}

#ifdef HEATMAP
				memset(heatmap,0,sizeof(heatmap));
#endif
		for(i=0;pre_mcmd[i].name;i++)
		{
			const char *tabs,*tabx;
			int	adj;

			if (pass == __command_hash_9)
			{
				h = mkhash(pre_mcmd[i].name);
#ifdef HEATMAP
				if (heatmapon > 0)
				{
					for(j=0;j<sizeof(heatmap);j++)
					{
						to_file(2,"%s%c",((j%32)==0) ? "\n" : "",(heatmap[j] > 0) ? (-1 + 'A' + heatmap[j]) : '.');
					}
					to_file(2,"\nend of heatmap for %s\n",pre_mcmd[i].name);
				}
#endif
				if (collis > mincoll)
					break;
				continue;
			}
			cmdstr = getsortedcommand(pass,&cmdidx);
			if (pass == __define_strng_5)
			{
			}
			if (pass == __define_print_3)
			{
				if (cmdstr)
				{
					adj = strlen(cmdstr);
					tabs = ((adj) < 7) ? "\t\t" : "\t";
					to_file(fd,"BEG const char C_%s[]%s\tMDEF(\"%s\");%s/""* %3i *""/\n",
						cmdstr,((adj + 3) < 8) ? "\t" : "",cmdstr,tabs,cmdcount);
					cmdcount++;
				}
			}
			if (pass == __struct_acces_2)
			{
				to_file(fd,"\t%i,\t/""* %s *""/\n",pre_mcmd[cmdidx].flags & CLEVEL,cmdstr);
			}
			if (pass == __struct_print_1)
			{
				char noargfunc[64];
				h = mkhash(cmdstr);
				hashmap[h] = i;

				memset(&v,0,sizeof(v));

				v.defaultaccess = pre_mcmd[cmdidx].flags & CLEVEL;
				/* + defaultaccess */
				if (v.defaultaccess >= 5) /* semi-public commands */
					v.cc = 1;
				if (v.defaultaccess >= 10) /* normal commands */
					v.pass = 1;

				v.dcc    = (pre_mcmd[cmdidx].flags & DCC)    ? 1 : 0;
				v.args   = (pre_mcmd[cmdidx].flags & CARGS)  ? 1 : 0;
				v.nopub  = (pre_mcmd[cmdidx].flags & NOPUB)  ? 1 : 0;
				v.nocmd  = (pre_mcmd[cmdidx].flags & NOCMD)  ? 1 : 0;
				v.gaxs   = (pre_mcmd[cmdidx].flags & GAXS)   ? 1 : 0;
				v.caxs   = (pre_mcmd[cmdidx].flags & CAXS)   ? 1 : 0;
				v.redir  = (pre_mcmd[cmdidx].flags & REDIR)  ? 1 : 0;
				v.lbuf   = (pre_mcmd[cmdidx].flags & LBUF)   ? 1 : 0;
				v.cbang  = (pre_mcmd[cmdidx].flags & CBANG)  ? 1 : 0;
				v.acchan = (pre_mcmd[cmdidx].flags & ACCHAN) ? 1 : 0;
				v.supres = (pre_mcmd[cmdidx].flags & SUPRES) ? 1 : 0;
				v.noargf = (pre_mcmd[cmdidx].flags & NOARGF) ? 1 : 0;

				sprintf(tmp,"%3i,%2i,%2i,%2i,%2i,%2i,%2i,%2i,%2i,%2i,%2i,%2i,%2i,%2i,%2i",
					v.defaultaccess,
					v.dcc,
					v.cc,
					v.pass,
					v.args,
					v.nopub,
					v.nocmd,
					v.gaxs,
					v.caxs,
					v.redir,
					v.lbuf,
					v.cbang,
					v.acchan,
					v.supres,
					v.noargf
					);

				tabs = "\t\t\t";

				adj = strlen(cmdstr);
				if (adj < 3)
					tabx = tabs + 1;
				else
				if (adj < 11)
					tabx = tabs + 2;
				else
					tabx = tabs + 3;

				if (v.noargf)
					sprintf(noargfunc,"\n\t\t\t%s_noargs",pre_mcmd[cmdidx].func);
				else
					strcpy(noargfunc," 0");
				adj = strlen(pre_mcmd[cmdidx].func);
				tabs += 1 + ((adj > 6));

				//to_file(fd,"/""* %3i=%3i *""/",h,i);
				to_file(fd,(pre_mcmd[cmdidx].cmdarg) ?
					"{ C_%s,%s\t%s,%s,%s%s\t, \"%s\"\t},\n" :
					"{ C_%s,%s\t%s,%s,%s%s\t},\n",
					cmdstr,
					tabx,
					pre_mcmd[cmdidx].func,
					noargfunc,
					tabs,
					tmp,
					pre_mcmd[cmdidx].cmdarg
				);
			}
			pre_mcmd[cmdidx].pass = pass;
		}
		if (pass == __define_strng_5)
		{
			/* nothing */;
		}
		if (pass == __define_print_3)
		{
			to_file(fd,"\n/""* number of builtin commands: %i *""/\n\n",cmdcount);
			if (cmdcount >= 255)
			{
				to_file(2,"gencmd: Hashmap overflow error\n");
				exit(66);
			}
			to_file(fd,"#ifdef MAIN_C\n\n");
		}
		if (pass == __struct_print_1)
		{
			to_file(fd,"{ NULL, }};\n\n");
		}
		if (pass == __struct_acces_2)
		{
			to_file(fd,"};\n\n");
		}
		if (pass == __command_hash_9)
		{
			if (collis > 0)
				pass = __command_hash_9 + 1;
			if (collis < mincoll)
			{
				mincoll = collis;
				to_file(fd,"\n");
			}
			if (collis == 0)
			{
				int cachefd;

				cachefd = open("hashdata.cache",O_WRONLY|O_CREAT|O_TRUNC,0644);
				write(cachefd,hashdata,sizeof(hashdata));
				close(cachefd);
			}
			to_file(2,"gencmd: Hash options tried: %8i, Collisions %4i, Best hash option so far %4i collisions%c",
				mx,collis,mincoll,(collis == 0) ? '\n' : '\r');
			mx++;
			collis = 0;
		}
		pass--;
	}
	to_file(fd,"#define LOCALHOST_ULONG %lu\n",inet_addr("127.1"));
	to_file(fd,"#else /""* MAIN_C *""/\n\n");
	to_file(fd,"extern OnMsg mcmd[];\n");
	to_file(fd,"extern OnMsg_access acmd[];\n\n");
	to_file(fd,"#endif /""* MAIN_C *""/\n\n");

			to_file(fd,"#if defined(COM_ONS_C) || defined(MEGA_C)\n\n");
			to_file(fd,"#define HASHDATAMASK\t\t%i\n",HASHDATAMASK);
			to_file(fd,"#define HASHDATASZ\t\t%i\n\nconst uint8_t hashdata[HASHDATASZ] =\n{",HASHDATASZ);
			for(i=0;i<HASHDATASZ;i++)
			{
				to_file(fd,"%s0x%02X%s",((i%16)==0) ? "\n\t" : "",hashdata[i],(i==HASHDATASZ-1) ? "" : ",");
			}
			to_file(fd,"\n};\n\n");

			to_file(fd,"const uint8_t hashmap[%i] =\n{",sizeof(hashmap));
			for(i=0;i<sizeof(hashmap);i++)
			{
				to_file(fd,"%s0x%02X%s",((i%16)==0) ? "\n\t" : "",hashmap[i],(i==511) ? "" : ",");
			}
			to_file(fd,"\n};\n\n");
			to_file(fd,"#endif /""* defined(COM_ONS_C) || defined(MEGA_C) *""/\n\n");

	to_file(fd,"#endif /""* not MCMD_H *""/\n\n");
	to_file(fd,"#endif /""* not TEST *""/\n\n");
	close(fd);
	exit(0);
}

void make_usercombo(void)
{
	usercombo combo;
	int	fd;

	unlink("usercombo.h");
	fd = open("usercombo.h",O_WRONLY|O_CREAT|O_TRUNC,0644);

	to_file(fd,"/""* This file is automatically generated from gencmd.c *""/\n");

	/* dont gatekeep these flags with ifdefs,
	 make userfiles compatible between different compiles */
	combo.comboflags = 0; combo.x.noshare = 1;
	to_file(fd,"#define COMBO_NOSHARE\t0x%x\n",combo.comboflags);
	combo.comboflags = 0; combo.x.readonly = 1;
	to_file(fd,"#define COMBO_READONLY\t0x%x\n",combo.comboflags);

	combo.comboflags = 0; combo.x.greetfile = 1;
	to_file(fd,"#define COMBO_GREETFILE\t0x%x\n",combo.comboflags);
	combo.comboflags = 0; combo.x.randline = 1;
	to_file(fd,"#define COMBO_RANDLINE\t0x%x\n",combo.comboflags);

	combo.comboflags = 0; combo.x.bounce = 1;
	to_file(fd,"#define COMBO_BOUNCE\t0x%x\n",combo.comboflags);

	combo.comboflags = 0; combo.x.echo = 1;
	to_file(fd,"#define COMBO_ECHO\t0x%x\n",combo.comboflags);
	combo.comboflags = 0; combo.x.aop = 1;
	to_file(fd,"#define COMBO_AOP\t0x%x\n",combo.comboflags);
	combo.comboflags = 0; combo.x.avoice = 1;
	to_file(fd,"#define COMBO_AVOICE\t0x%x\n",combo.comboflags);

	close(fd);
	exit(0);
}

void test_help(void)
{
	char	tmp[PATH_MAX];
        struct stat st;
        int     i,r;

	for(i=0;pre_mcmd[i].name;i++)
	{
		sprintf(tmp,"../help/%s",pre_mcmd[i].name);
		r = stat(tmp,&st);

		if (r == -1 && errno == ENOENT)
			to_file(1,"help for %s is missing\n",pre_mcmd[i].name);
	}
	exit(0);
}

const char *month[] = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
int hourampm[24] = { 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 };

void datestamp(void)
{
	char	str[100],*th;
	struct tm *t;
	time_t	now;

	time(&now);
	t = localtime(&now);

	switch(t->tm_mday)
	{
	case 31:
	case 21:
	case 1:th="st";break;
	case 22:
	case 2:th="nd";break;
	case 23:
	case 3:th="rd";break;
	default:th="th";
	}
	to_file(1,"\"%s %i%s, %i at %i:%02i%s\"",month[t->tm_mon],t->tm_mday,th,
		t->tm_year + 1900,hourampm[t->tm_hour],t->tm_min,(t->tm_hour <= 11) ? "am" : "pm");
}

#ifndef HAVE_GIT

const char *srcfile[] = { "../configure", "../Makefile", "Makefile.in", "alias.c", "auth.c", "bounce.c", "calc.c",
	"channel.c", "config.h", "config.h.in", "core.c", "ctcp.c", "debug.c", "defines.h", "dns.c", "function.c",
	"gencmd.c", "global.h", "greet.c", "h.h", "help.c", "hostinfo.c", "io.c", "irc.c", "lib/string.c", "main.c",
	"net.c", "note.c", "ons.c", "parse.c", "partyline.c", "perl.c", "prot.c", "python.c", "reset.c", "seen.c",
	"settings.h", "shit.c", "spy.c", "structs.h", "tcl.c", "text.h", "toybox.c", "uptime.c", "usage.h", "user.c",
	"vars.c", "web.c", NULL };

int linecount;

int countcallback(char *line)
{
	linecount++;
	return(FALSE);
}

int countlines(const char *filename)
{
	int	fd;

	linecount = 0;
	if ((fd = open(filename,O_RDONLY)) < 0)
		return(0);
	readline(fd,&countcallback); /* readline closes fd */
	return(linecount);
}

#endif

void githash(void)
{
	int	i,fd,verlines,sloc;

#ifdef HAVE_GIT
	system("./lib/git.sh > githash.h");
#else
	sloc = verlines = countlines("../VERSIONS");
	for(i=0;srcfile[i];i++)
		sloc += countlines(srcfile[i]);

	fd = open("githash.h",O_WRONLY|O_CREAT|O_TRUNC,0644);
	to_file(fd,"#define GITHASH \" (src:%i/%i)\"\n",verlines,sloc);
	close(fd);
#endif
}

int main(int argc, char **argv)
{
	randfd = -1;
	mx = 0;
	mincoll = 666666;
	heatmapon = 0;

	if (argv[1])
	{
		if (strcmp(argv[1],"usercombo.h") == 0)
			make_usercombo();

		if (strcmp(argv[1],"mcmd.h") == 0)
			make_mcmd(0);

		if (strcmp(argv[1],"testhelp") == 0)
			test_help();

		if (strcmp(argv[1],"date") == 0)
			datestamp();

		if (strcmp(argv[1],"githash.h") == 0)
			githash();

		if (strcmp(argv[1],"heatmap") == 0)
		{
			heatmapon = 1;
			make_mcmd(1);
		}
	}
	else
	{
		make_mcmd(1);
	}
	return(0);
}
